version: "3.1"
services: 
  portfolio-frontend: 
    # build: ./frontend 
    image: mpmeissner/portfolio-frontend:2.1
    ports: 
      - 3000:3000
  portfolio-database: 
    # build: ./database
    image: mpmeissner/portfolio-database:1.2
    ports: 
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password 
    restart: always
    volumes: 
      - db-data:/var/lib/mysql
  portfolio-backend: 
    # build: ./backend
    image: mpmeissner/portfolio-backend:1.5
    ports: 
      - 8000:8000 
    restart: always 
    depends_on:
      - "portfolio-database"
    command: >
      sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
volumes: 
  db-data: 