version: "3.1"
services: 
  portfolio-frontend: 
    build: ./frontend 
    ports: 
      -3301:3001
    image: mpmeissner/portfolio-frontend:1.3
  portfolio-database: 
    build: ./backend
    image: mpmeissner/portfolio-backend:1.6
    ports: 
      - 3307:3306
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root 
  portfolio-backend: 
    build: ./backend 
    image: mpmeissner/portfolio-backend:1.6 
    ports: 
      -8000:8000 
    restart: always 
    command: >
      sh -c 'python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000'
    depends_on:
      - 'portfolio_database'