FROM python:alpine3.18 


WORKDIR /app 

COPY requirements.txt ./

COPY ./portfolio ./portfolio 

COPY . .


RUN pip install -r requirements.txt


CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]

##Use this for Dockerfile for DjangoRestFramework apps